### ISSUE TITLE
Gold Watch Image is missing

### ISSUE THREAD

**Issue by assaultboy** [usecforce/USEC_IssuesWiki#21]
The Image for the gold watch is broken on the [award page](http://www.usecforce.com/roster/?v=135&g=decoration&o=180)

**Comment by MattLightfoot** [comment]
Had a look into this issue, the issue seems to reside with the "Special" Decoration type, this is what defines where it pulls the image from.

I tested switching it to medals and moving the source image there and it worked. This however then shows it in the list of Medals. I'd prefer it stayed as a hidden award, will try to find the file that defines where to pull the images from.

**Comment by jonpas** [comment]
I have a feeling I know what it is. I'll check when I get home.

**Comment by MattLightfoot** [comment]
I believe it's an issue with the definition in the file for the decorations recipients page, but I'm not sure where that is.

**Comment by jonpas** [comment]
Fixed. The issue was in wrong folder and file name.

There is one of those 3D images with the background though, but that requires code changes, let me know if wanted (they look pretty neat).
