### ISSUE TITLE
Old Citation ribbon images missing

### ISSUE THREAD

**Issue by assaultboy** [usecforce/USEC_IssuesWiki#30]
On [Sam Maunder's](http://www.usecforce.com/profile/?id=1507) showcase, he has a Chief of Staff ribbon that is broken.

![image](https://cloud.githubusercontent.com/assets/11630560/7028456/f25dc468-dd23-11e4-9c6e-f1ef928529b9.png)

It appears to be an deprecated version of the Chief of Staff Citation Ribbon.

[Old](http://www.usecforce.com/roster/?v=53&g=decoration)

[New](http://www.usecforce.com/roster/?v=191&g=decoration&o=401)

**Comment by jonpas** [comment]
I duplicated the missing one with new ribbon design by Rory... why the hell do we have 2 different versions of same citation though...

**Comment by assaultboy** [comment]
It looks like a bunch of old ribbons were just remade for some reason. I think all the command citation ones have duplicates

**Comment by codethirteen** [comment]
Yeah I dealt with some of this yesterday reworking the decorations page. Another broken image example: http://www.usecforce.com/roster/?v=52&g=decoration

**Comment by jonpas** [comment]
Okay, now I know why Arden kept the old old citation ribbons there as well. :grin: 

Basically what happened: Rory made new ribbons (because Arden's didn't have variants when you have multiple, old old ones did though) and so I archived old old and Arden's, old old ones are still needed though, unless you want to fix them manually @codethirteen in the code?

EDIT: I've duplicated Rory's for now.
