### ISSUE TITLE
Getting kicked due to throwing chemlights at base

### ISSUE THREAD

**Issue by Dimaslg** [usecforce/USEC_IssuesWiki#46]
I know there has to be some kind of punish if we do mess at the base, but at night theres no lights at base, so if we respawn there, come back without NVGs or want to leave the NVGs in the crate, we should be able to throw some chem-lights around to get some light. Also dont know how its configured cuz i never misfired at base, but one shot and get kicked sound a bit extreme, you can need to alt-tab to check the spreadsheet and misfire by mistake, it happened to everyone. We should be all adults and know what we can and cannot do at base and if someone mess around too much ban him from the force-wide could be a solution instead of something automatic that cannot difference between mistakes and being a child.

One of the possible solutions could be add some light poles at base, or some source of light at night.

https://www.youtube.com/watch?v=nDpv3gy-8Tg

**Comment by jonpas** [comment]
Fixed for next week.

**Comment by jonpas** [comment]
@Dimaslg 

> Also dont know how its configured cuz i never misfired at base, but one shot and get kicked sound a bit extreme, you can need to alt-tab to check the spreadsheet and misfire by mistake, it happened to everyone.

You can put your weapon on the back and prevent firing that way, additionally you can lock your weapon (or that's ACE-only, I am not sure). It happens to me quite a lot as well, it just means I have to be more careful.

> We should be all adults and know what we can and cannot do at base and if someone mess around too much ban him from the force-wide could be a solution instead of something automatic that cannot difference between mistakes and being a child.

We didn't implement it earlier because we believed a hint will be enough to name-shame whoever does, that apparently wasn't enough as you could see quite a lot of people shooting for no reason (rarely, but it did happen).

> One of the possible solutions could be add some light poles at base, or some source of light at night.

Pitch it over to our mission makers. :grinning:
